

def do_error(*args, **kwargs):
    raise Exception("Test exception.")
